package com.nesder.dao.repository;

import com.nesder.dao.entity.Apikey;
import com.nesder.dao.entity.ApikeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApikeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    long countByExample(ApikeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int deleteByExample(ApikeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer apikey_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int insert(Apikey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int insertSelective(Apikey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    List<Apikey> selectByExample(ApikeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    Apikey selectByPrimaryKey(Integer apikey_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Apikey record, @Param("example") ApikeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Apikey record, @Param("example") ApikeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Apikey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.apikey
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Apikey record);
}