package com.nesder.dao.repository;

import com.nesder.dao.entity.ArticleMark;
import com.nesder.dao.entity.ArticleMarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    long countByExample(ArticleMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    int insert(ArticleMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    int insertSelective(ArticleMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    List<ArticleMark> selectByExample(ArticleMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleMark record, @Param("example") ArticleMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.article_mark
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleMark record, @Param("example") ArticleMarkExample example);
}