package com.nesder.dao.repository;

import com.nesder.dao.entity.BrowseHistory;
import com.nesder.dao.entity.BrowseHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrowseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    long countByExample(BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    int deleteByExample(BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    int insert(BrowseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    int insertSelective(BrowseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    List<BrowseHistory> selectByExample(BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BrowseHistory record, @Param("example") BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.browse_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BrowseHistory record, @Param("example") BrowseHistoryExample example);
}