package com.nesder.dao.repository;

import com.nesder.dao.entity.FllowAccount;
import com.nesder.dao.entity.FllowAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FllowAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    long countByExample(FllowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    int deleteByExample(FllowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    int insert(FllowAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    int insertSelective(FllowAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    List<FllowAccount> selectByExample(FllowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FllowAccount record, @Param("example") FllowAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.fllow_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FllowAccount record, @Param("example") FllowAccountExample example);
}