package com.nesder.dao.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.nesder.dao.entity.Module;
import com.nesder.dao.entity.ModuleExample;

public interface ModuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	long countByExample(ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int deleteByExample(ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int insert(Module record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int insertSelective(Module record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	List<Module> selectByExample(ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	Module selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Module record, @Param("example") ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Module record, @Param("example") ModuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Module record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.module
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Module record);
}