package com.nesder.dao.repository;

import com.nesder.dao.entity.PostMark;
import com.nesder.dao.entity.PostMarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    long countByExample(PostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int deleteByExample(PostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer post_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int insert(PostMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int insertSelective(PostMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    List<PostMark> selectByExample(PostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    PostMark selectByPrimaryKey(Integer post_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PostMark record, @Param("example") PostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PostMark record, @Param("example") PostMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PostMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostMark record);
}