package com.nesder.dao.repository;

import com.nesder.dao.entity.PostMediafiles;
import com.nesder.dao.entity.PostMediafilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostMediafilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    long countByExample(PostMediafilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int deleteByExample(PostMediafilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer post_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int insert(PostMediafiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int insertSelective(PostMediafiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    List<PostMediafiles> selectByExample(PostMediafilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    PostMediafiles selectByPrimaryKey(Integer post_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PostMediafiles record, @Param("example") PostMediafilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PostMediafiles record, @Param("example") PostMediafilesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PostMediafiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.post_mediafiles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostMediafiles record);
}