package com.nesder.dao.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.nesder.dao.entity.Reply2Reply;
import com.nesder.dao.entity.Reply2ReplyExample;

public interface Reply2ReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	long countByExample(Reply2ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int deleteByExample(Reply2ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int insert(Reply2Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int insertSelective(Reply2Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	List<Reply2Reply> selectByExample(Reply2ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	Reply2Reply selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Reply2Reply record, @Param("example") Reply2ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Reply2Reply record, @Param("example") Reply2ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Reply2Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.reply_2_reply
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Reply2Reply record);
}