package com.nesder.dao.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.account
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.account
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.account
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public AccountExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.account
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.account
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAccount_idIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccount_idIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccount_idEqualTo(String value) {
			addCriterion("account_id =", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idNotEqualTo(String value) {
			addCriterion("account_id <>", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idGreaterThan(String value) {
			addCriterion("account_id >", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idGreaterThanOrEqualTo(String value) {
			addCriterion("account_id >=", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idLessThan(String value) {
			addCriterion("account_id <", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idLessThanOrEqualTo(String value) {
			addCriterion("account_id <=", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idLike(String value) {
			addCriterion("account_id like", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idNotLike(String value) {
			addCriterion("account_id not like", value, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idIn(List<String> values) {
			addCriterion("account_id in", values, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idNotIn(List<String> values) {
			addCriterion("account_id not in", values, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idBetween(String value1, String value2) {
			addCriterion("account_id between", value1, value2, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_idNotBetween(String value1, String value2) {
			addCriterion("account_id not between", value1, value2, "account_id");
			return (Criteria) this;
		}

		public Criteria andAccount_typeIsNull() {
			addCriterion("account_type is null");
			return (Criteria) this;
		}

		public Criteria andAccount_typeIsNotNull() {
			addCriterion("account_type is not null");
			return (Criteria) this;
		}

		public Criteria andAccount_typeEqualTo(Integer value) {
			addCriterion("account_type =", value, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeNotEqualTo(Integer value) {
			addCriterion("account_type <>", value, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeGreaterThan(Integer value) {
			addCriterion("account_type >", value, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeGreaterThanOrEqualTo(Integer value) {
			addCriterion("account_type >=", value, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeLessThan(Integer value) {
			addCriterion("account_type <", value, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeLessThanOrEqualTo(Integer value) {
			addCriterion("account_type <=", value, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeIn(List<Integer> values) {
			addCriterion("account_type in", values, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeNotIn(List<Integer> values) {
			addCriterion("account_type not in", values, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeBetween(Integer value1, Integer value2) {
			addCriterion("account_type between", value1, value2, "account_type");
			return (Criteria) this;
		}

		public Criteria andAccount_typeNotBetween(Integer value1, Integer value2) {
			addCriterion("account_type not between", value1, value2, "account_type");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andNick_nameIsNull() {
			addCriterion("nick_name is null");
			return (Criteria) this;
		}

		public Criteria andNick_nameIsNotNull() {
			addCriterion("nick_name is not null");
			return (Criteria) this;
		}

		public Criteria andNick_nameEqualTo(String value) {
			addCriterion("nick_name =", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameNotEqualTo(String value) {
			addCriterion("nick_name <>", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameGreaterThan(String value) {
			addCriterion("nick_name >", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameGreaterThanOrEqualTo(String value) {
			addCriterion("nick_name >=", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameLessThan(String value) {
			addCriterion("nick_name <", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameLessThanOrEqualTo(String value) {
			addCriterion("nick_name <=", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameLike(String value) {
			addCriterion("nick_name like", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameNotLike(String value) {
			addCriterion("nick_name not like", value, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameIn(List<String> values) {
			addCriterion("nick_name in", values, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameNotIn(List<String> values) {
			addCriterion("nick_name not in", values, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameBetween(String value1, String value2) {
			addCriterion("nick_name between", value1, value2, "nick_name");
			return (Criteria) this;
		}

		public Criteria andNick_nameNotBetween(String value1, String value2) {
			addCriterion("nick_name not between", value1, value2, "nick_name");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Integer value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Integer value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Integer value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Integer value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Integer value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Integer> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Integer> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Integer value1, Integer value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Integer value1, Integer value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andCreate_dateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreate_dateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreate_dateEqualTo(Date value) {
			addCriterion("create_date =", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateGreaterThan(Date value) {
			addCriterion("create_date >", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateLessThan(Date value) {
			addCriterion("create_date <", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateIn(List<Date> values) {
			addCriterion("create_date in", values, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "create_date");
			return (Criteria) this;
		}

		public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "create_date");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(Integer value) {
			addCriterion("age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(Integer value) {
			addCriterion("age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(Integer value) {
			addCriterion("age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
			addCriterion("age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(Integer value) {
			addCriterion("age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(Integer value) {
			addCriterion("age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<Integer> values) {
			addCriterion("age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<Integer> values) {
			addCriterion("age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(Integer value1, Integer value2) {
			addCriterion("age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(Integer value1, Integer value2) {
			addCriterion("age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andIntroductionIsNull() {
			addCriterion("introduction is null");
			return (Criteria) this;
		}

		public Criteria andIntroductionIsNotNull() {
			addCriterion("introduction is not null");
			return (Criteria) this;
		}

		public Criteria andIntroductionEqualTo(String value) {
			addCriterion("introduction =", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotEqualTo(String value) {
			addCriterion("introduction <>", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionGreaterThan(String value) {
			addCriterion("introduction >", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
			addCriterion("introduction >=", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionLessThan(String value) {
			addCriterion("introduction <", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionLessThanOrEqualTo(String value) {
			addCriterion("introduction <=", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionLike(String value) {
			addCriterion("introduction like", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotLike(String value) {
			addCriterion("introduction not like", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionIn(List<String> values) {
			addCriterion("introduction in", values, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotIn(List<String> values) {
			addCriterion("introduction not in", values, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionBetween(String value1, String value2) {
			addCriterion("introduction between", value1, value2, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotBetween(String value1, String value2) {
			addCriterion("introduction not between", value1, value2, "introduction");
			return (Criteria) this;
		}

		public Criteria andLogin_authIsNull() {
			addCriterion("login_auth is null");
			return (Criteria) this;
		}

		public Criteria andLogin_authIsNotNull() {
			addCriterion("login_auth is not null");
			return (Criteria) this;
		}

		public Criteria andLogin_authEqualTo(Integer value) {
			addCriterion("login_auth =", value, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authNotEqualTo(Integer value) {
			addCriterion("login_auth <>", value, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authGreaterThan(Integer value) {
			addCriterion("login_auth >", value, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authGreaterThanOrEqualTo(Integer value) {
			addCriterion("login_auth >=", value, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authLessThan(Integer value) {
			addCriterion("login_auth <", value, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authLessThanOrEqualTo(Integer value) {
			addCriterion("login_auth <=", value, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authIn(List<Integer> values) {
			addCriterion("login_auth in", values, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authNotIn(List<Integer> values) {
			addCriterion("login_auth not in", values, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authBetween(Integer value1, Integer value2) {
			addCriterion("login_auth between", value1, value2, "login_auth");
			return (Criteria) this;
		}

		public Criteria andLogin_authNotBetween(Integer value1, Integer value2) {
			addCriterion("login_auth not between", value1, value2, "login_auth");
			return (Criteria) this;
		}

		public Criteria andAvatarurlIsNull() {
			addCriterion("avatarurl is null");
			return (Criteria) this;
		}

		public Criteria andAvatarurlIsNotNull() {
			addCriterion("avatarurl is not null");
			return (Criteria) this;
		}

		public Criteria andAvatarurlEqualTo(String value) {
			addCriterion("avatarurl =", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotEqualTo(String value) {
			addCriterion("avatarurl <>", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlGreaterThan(String value) {
			addCriterion("avatarurl >", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlGreaterThanOrEqualTo(String value) {
			addCriterion("avatarurl >=", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlLessThan(String value) {
			addCriterion("avatarurl <", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlLessThanOrEqualTo(String value) {
			addCriterion("avatarurl <=", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlLike(String value) {
			addCriterion("avatarurl like", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotLike(String value) {
			addCriterion("avatarurl not like", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlIn(List<String> values) {
			addCriterion("avatarurl in", values, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotIn(List<String> values) {
			addCriterion("avatarurl not in", values, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlBetween(String value1, String value2) {
			addCriterion("avatarurl between", value1, value2, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotBetween(String value1, String value2) {
			addCriterion("avatarurl not between", value1, value2, "avatarurl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.account
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.account
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}