package com.nesder.dao.domain;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.marks
	 * @mbg.generated
	 */
	private Integer marks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.browse
	 * @mbg.generated
	 */
	private Integer browse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.create_date
	 * @mbg.generated
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.modify_date
	 * @mbg.generated
	 */
	private Date modify_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.enable_edit
	 * @mbg.generated
	 */
	private Boolean enable_edit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.channel_id
	 * @mbg.generated
	 */
	private Integer channel_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.article.created_account
	 * @mbg.generated
	 */
	private Integer created_account;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.id
	 * @return  the value of public.article.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.id
	 * @param id  the value for public.article.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.title
	 * @return  the value of public.article.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.title
	 * @param title  the value for public.article.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.marks
	 * @return  the value of public.article.marks
	 * @mbg.generated
	 */
	public Integer getMarks() {
		return marks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.marks
	 * @param marks  the value for public.article.marks
	 * @mbg.generated
	 */
	public void setMarks(Integer marks) {
		this.marks = marks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.content
	 * @return  the value of public.article.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.content
	 * @param content  the value for public.article.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.browse
	 * @return  the value of public.article.browse
	 * @mbg.generated
	 */
	public Integer getBrowse() {
		return browse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.browse
	 * @param browse  the value for public.article.browse
	 * @mbg.generated
	 */
	public void setBrowse(Integer browse) {
		this.browse = browse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.create_date
	 * @return  the value of public.article.create_date
	 * @mbg.generated
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.create_date
	 * @param create_date  the value for public.article.create_date
	 * @mbg.generated
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.modify_date
	 * @return  the value of public.article.modify_date
	 * @mbg.generated
	 */
	public Date getModify_date() {
		return modify_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.modify_date
	 * @param modify_date  the value for public.article.modify_date
	 * @mbg.generated
	 */
	public void setModify_date(Date modify_date) {
		this.modify_date = modify_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.enable_edit
	 * @return  the value of public.article.enable_edit
	 * @mbg.generated
	 */
	public Boolean getEnable_edit() {
		return enable_edit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.enable_edit
	 * @param enable_edit  the value for public.article.enable_edit
	 * @mbg.generated
	 */
	public void setEnable_edit(Boolean enable_edit) {
		this.enable_edit = enable_edit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.channel_id
	 * @return  the value of public.article.channel_id
	 * @mbg.generated
	 */
	public Integer getChannel_id() {
		return channel_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.channel_id
	 * @param channel_id  the value for public.article.channel_id
	 * @mbg.generated
	 */
	public void setChannel_id(Integer channel_id) {
		this.channel_id = channel_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.article.created_account
	 * @return  the value of public.article.created_account
	 * @mbg.generated
	 */
	public Integer getCreated_account() {
		return created_account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.article.created_account
	 * @param created_account  the value for public.article.created_account
	 * @mbg.generated
	 */
	public void setCreated_account(Integer created_account) {
		this.created_account = created_account;
	}
}