package com.nesder.dao.entity;

import java.util.Date;

public class Apikey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.apikey.apikey_id
     *
     * @mbg.generated
     */
    private Integer apikey_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.apikey.account_id
     *
     * @mbg.generated
     */
    private Integer account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.apikey.apikey
     *
     * @mbg.generated
     */
    private String apikey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.apikey.authority_key
     *
     * @mbg.generated
     */
    private String authority_key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.apikey.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.apikey.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.apikey.apikey_id
     *
     * @return the value of public.apikey.apikey_id
     *
     * @mbg.generated
     */
    public Integer getApikey_id() {
        return apikey_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.apikey.apikey_id
     *
     * @param apikey_id the value for public.apikey.apikey_id
     *
     * @mbg.generated
     */
    public void setApikey_id(Integer apikey_id) {
        this.apikey_id = apikey_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.apikey.account_id
     *
     * @return the value of public.apikey.account_id
     *
     * @mbg.generated
     */
    public Integer getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.apikey.account_id
     *
     * @param account_id the value for public.apikey.account_id
     *
     * @mbg.generated
     */
    public void setAccount_id(Integer account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.apikey.apikey
     *
     * @return the value of public.apikey.apikey
     *
     * @mbg.generated
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.apikey.apikey
     *
     * @param apikey the value for public.apikey.apikey
     *
     * @mbg.generated
     */
    public void setApikey(String apikey) {
        this.apikey = apikey == null ? null : apikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.apikey.authority_key
     *
     * @return the value of public.apikey.authority_key
     *
     * @mbg.generated
     */
    public String getAuthority_key() {
        return authority_key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.apikey.authority_key
     *
     * @param authority_key the value for public.apikey.authority_key
     *
     * @mbg.generated
     */
    public void setAuthority_key(String authority_key) {
        this.authority_key = authority_key == null ? null : authority_key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.apikey.remark
     *
     * @return the value of public.apikey.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.apikey.remark
     *
     * @param remark the value for public.apikey.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.apikey.create_date
     *
     * @return the value of public.apikey.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.apikey.create_date
     *
     * @param create_date the value for public.apikey.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}