package com.nesder.dao.entity;

import java.util.Date;

public class ArticleMark {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.article_mark.aid
     *
     * @mbg.generated
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.article_mark.marks
     *
     * @mbg.generated
     */
    private Boolean marks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.article_mark.likes
     *
     * @mbg.generated
     */
    private Boolean likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.article_mark.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.article_mark.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.article_mark.aid
     *
     * @return the value of public.article_mark.aid
     *
     * @mbg.generated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.article_mark.aid
     *
     * @param aid the value for public.article_mark.aid
     *
     * @mbg.generated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.article_mark.marks
     *
     * @return the value of public.article_mark.marks
     *
     * @mbg.generated
     */
    public Boolean getMarks() {
        return marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.article_mark.marks
     *
     * @param marks the value for public.article_mark.marks
     *
     * @mbg.generated
     */
    public void setMarks(Boolean marks) {
        this.marks = marks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.article_mark.likes
     *
     * @return the value of public.article_mark.likes
     *
     * @mbg.generated
     */
    public Boolean getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.article_mark.likes
     *
     * @param likes the value for public.article_mark.likes
     *
     * @mbg.generated
     */
    public void setLikes(Boolean likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.article_mark.uid
     *
     * @return the value of public.article_mark.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.article_mark.uid
     *
     * @param uid the value for public.article_mark.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.article_mark.create_date
     *
     * @return the value of public.article_mark.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.article_mark.create_date
     *
     * @param create_date the value for public.article_mark.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}