package com.nesder.dao.entity;

import java.util.Date;

public class BrowseHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.browse_history.browsedate
	 * @mbg.generated
	 */
	private Date browsedate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.browse_history.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.browse_history.aid
	 * @mbg.generated
	 */
	private Integer aid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.browse_history.browsedate
	 * @return  the value of public.browse_history.browsedate
	 * @mbg.generated
	 */
	public Date getBrowsedate() {
		return browsedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.browse_history.browsedate
	 * @param browsedate  the value for public.browse_history.browsedate
	 * @mbg.generated
	 */
	public void setBrowsedate(Date browsedate) {
		this.browsedate = browsedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.browse_history.uid
	 * @return  the value of public.browse_history.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.browse_history.uid
	 * @param uid  the value for public.browse_history.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.browse_history.aid
	 * @return  the value of public.browse_history.aid
	 * @mbg.generated
	 */
	public Integer getAid() {
		return aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.browse_history.aid
	 * @param aid  the value for public.browse_history.aid
	 * @mbg.generated
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}
}