package com.nesder.dao.entity;

import java.util.Date;

public class BrowseHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.account_id
     *
     * @mbg.generated
     */
    private Integer account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.post_id
     *
     * @mbg.generated
     */
    private Integer post_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.modify_date
     *
     * @mbg.generated
     */
    private Date modify_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.account_id
     *
     * @return the value of public.browse_history.account_id
     *
     * @mbg.generated
     */
    public Integer getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.account_id
     *
     * @param account_id the value for public.browse_history.account_id
     *
     * @mbg.generated
     */
    public void setAccount_id(Integer account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.post_id
     *
     * @return the value of public.browse_history.post_id
     *
     * @mbg.generated
     */
    public Integer getPost_id() {
        return post_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.post_id
     *
     * @param post_id the value for public.browse_history.post_id
     *
     * @mbg.generated
     */
    public void setPost_id(Integer post_id) {
        this.post_id = post_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.modify_date
     *
     * @return the value of public.browse_history.modify_date
     *
     * @mbg.generated
     */
    public Date getModify_date() {
        return modify_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.modify_date
     *
     * @param modify_date the value for public.browse_history.modify_date
     *
     * @mbg.generated
     */
    public void setModify_date(Date modify_date) {
        this.modify_date = modify_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.create_date
     *
     * @return the value of public.browse_history.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.create_date
     *
     * @param create_date the value for public.browse_history.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}