package com.nesder.dao.entity;

import java.util.Date;

public class BrowseHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.browse_history.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.uid
     *
     * @return the value of public.browse_history.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.uid
     *
     * @param uid the value for public.browse_history.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.pid
     *
     * @return the value of public.browse_history.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.pid
     *
     * @param pid the value for public.browse_history.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.browse_history.create_date
     *
     * @return the value of public.browse_history.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.browse_history.create_date
     *
     * @param create_date the value for public.browse_history.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}