package com.nesder.dao.entity;

import java.util.Date;

public class Channel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.channel.channel_id
     *
     * @mbg.generated
     */
    private Integer channel_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.channel.channel_name
     *
     * @mbg.generated
     */
    private String channel_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.channel.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.channel.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.channel.account_id
     *
     * @mbg.generated
     */
    private Integer account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.channel.fid
     *
     * @mbg.generated
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.channel.channel_id
     *
     * @return the value of public.channel.channel_id
     *
     * @mbg.generated
     */
    public Integer getChannel_id() {
        return channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.channel.channel_id
     *
     * @param channel_id the value for public.channel.channel_id
     *
     * @mbg.generated
     */
    public void setChannel_id(Integer channel_id) {
        this.channel_id = channel_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.channel.channel_name
     *
     * @return the value of public.channel.channel_name
     *
     * @mbg.generated
     */
    public String getChannel_name() {
        return channel_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.channel.channel_name
     *
     * @param channel_name the value for public.channel.channel_name
     *
     * @mbg.generated
     */
    public void setChannel_name(String channel_name) {
        this.channel_name = channel_name == null ? null : channel_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.channel.create_date
     *
     * @return the value of public.channel.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.channel.create_date
     *
     * @param create_date the value for public.channel.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.channel.introduction
     *
     * @return the value of public.channel.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.channel.introduction
     *
     * @param introduction the value for public.channel.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.channel.account_id
     *
     * @return the value of public.channel.account_id
     *
     * @mbg.generated
     */
    public Integer getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.channel.account_id
     *
     * @param account_id the value for public.channel.account_id
     *
     * @mbg.generated
     */
    public void setAccount_id(Integer account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.channel.fid
     *
     * @return the value of public.channel.fid
     *
     * @mbg.generated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.channel.fid
     *
     * @param fid the value for public.channel.fid
     *
     * @mbg.generated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}