package com.nesder.dao.entity;

import java.util.Date;

public class ChatContent {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_content.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_content.content
	 * @mbg.generated
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_content.create_date
	 * @mbg.generated
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_content.chat_group_id
	 * @mbg.generated
	 */
	private Integer chat_group_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_content.created_account
	 * @mbg.generated
	 */
	private Integer created_account;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_content.id
	 * @return  the value of public.chat_content.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_content.id
	 * @param id  the value for public.chat_content.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_content.content
	 * @return  the value of public.chat_content.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_content.content
	 * @param content  the value for public.chat_content.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_content.create_date
	 * @return  the value of public.chat_content.create_date
	 * @mbg.generated
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_content.create_date
	 * @param create_date  the value for public.chat_content.create_date
	 * @mbg.generated
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_content.chat_group_id
	 * @return  the value of public.chat_content.chat_group_id
	 * @mbg.generated
	 */
	public Integer getChat_group_id() {
		return chat_group_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_content.chat_group_id
	 * @param chat_group_id  the value for public.chat_content.chat_group_id
	 * @mbg.generated
	 */
	public void setChat_group_id(Integer chat_group_id) {
		this.chat_group_id = chat_group_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_content.created_account
	 * @return  the value of public.chat_content.created_account
	 * @mbg.generated
	 */
	public Integer getCreated_account() {
		return created_account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_content.created_account
	 * @param created_account  the value for public.chat_content.created_account
	 * @mbg.generated
	 */
	public void setCreated_account(Integer created_account) {
		this.created_account = created_account;
	}
}