package com.nesder.dao.entity;

import java.util.Date;

public class ChatGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.group_account_type
	 * @mbg.generated
	 */
	private Integer group_account_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.gname
	 * @mbg.generated
	 */
	private String gname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.create_date
	 * @mbg.generated
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.introduction
	 * @mbg.generated
	 */
	private String introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.avatorurl
	 * @mbg.generated
	 */
	private String avatorurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.created_account
	 * @mbg.generated
	 */
	private Integer created_account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.chat_group.chat_type
	 * @mbg.generated
	 */
	private Integer chat_type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.id
	 * @return  the value of public.chat_group.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.id
	 * @param id  the value for public.chat_group.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.group_account_type
	 * @return  the value of public.chat_group.group_account_type
	 * @mbg.generated
	 */
	public Integer getGroup_account_type() {
		return group_account_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.group_account_type
	 * @param group_account_type  the value for public.chat_group.group_account_type
	 * @mbg.generated
	 */
	public void setGroup_account_type(Integer group_account_type) {
		this.group_account_type = group_account_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.gname
	 * @return  the value of public.chat_group.gname
	 * @mbg.generated
	 */
	public String getGname() {
		return gname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.gname
	 * @param gname  the value for public.chat_group.gname
	 * @mbg.generated
	 */
	public void setGname(String gname) {
		this.gname = gname == null ? null : gname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.create_date
	 * @return  the value of public.chat_group.create_date
	 * @mbg.generated
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.create_date
	 * @param create_date  the value for public.chat_group.create_date
	 * @mbg.generated
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.introduction
	 * @return  the value of public.chat_group.introduction
	 * @mbg.generated
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.introduction
	 * @param introduction  the value for public.chat_group.introduction
	 * @mbg.generated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.avatorurl
	 * @return  the value of public.chat_group.avatorurl
	 * @mbg.generated
	 */
	public String getAvatorurl() {
		return avatorurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.avatorurl
	 * @param avatorurl  the value for public.chat_group.avatorurl
	 * @mbg.generated
	 */
	public void setAvatorurl(String avatorurl) {
		this.avatorurl = avatorurl == null ? null : avatorurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.created_account
	 * @return  the value of public.chat_group.created_account
	 * @mbg.generated
	 */
	public Integer getCreated_account() {
		return created_account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.created_account
	 * @param created_account  the value for public.chat_group.created_account
	 * @mbg.generated
	 */
	public void setCreated_account(Integer created_account) {
		this.created_account = created_account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.chat_group.chat_type
	 * @return  the value of public.chat_group.chat_type
	 * @mbg.generated
	 */
	public Integer getChat_type() {
		return chat_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.chat_group.chat_type
	 * @param chat_type  the value for public.chat_group.chat_type
	 * @mbg.generated
	 */
	public void setChat_type(Integer chat_type) {
		this.chat_type = chat_type;
	}
}