package com.nesder.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public ChatGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChat_group_idIsNull() {
            addCriterion("chat_group_id is null");
            return (Criteria) this;
        }

        public Criteria andChat_group_idIsNotNull() {
            addCriterion("chat_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andChat_group_idEqualTo(Integer value) {
            addCriterion("chat_group_id =", value, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idNotEqualTo(Integer value) {
            addCriterion("chat_group_id <>", value, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idGreaterThan(Integer value) {
            addCriterion("chat_group_id >", value, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("chat_group_id >=", value, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idLessThan(Integer value) {
            addCriterion("chat_group_id <", value, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idLessThanOrEqualTo(Integer value) {
            addCriterion("chat_group_id <=", value, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idIn(List<Integer> values) {
            addCriterion("chat_group_id in", values, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idNotIn(List<Integer> values) {
            addCriterion("chat_group_id not in", values, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idBetween(Integer value1, Integer value2) {
            addCriterion("chat_group_id between", value1, value2, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andChat_group_idNotBetween(Integer value1, Integer value2) {
            addCriterion("chat_group_id not between", value1, value2, "chat_group_id");
            return (Criteria) this;
        }

        public Criteria andCreated_accountIsNull() {
            addCriterion("created_account is null");
            return (Criteria) this;
        }

        public Criteria andCreated_accountIsNotNull() {
            addCriterion("created_account is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_accountEqualTo(Integer value) {
            addCriterion("created_account =", value, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountNotEqualTo(Integer value) {
            addCriterion("created_account <>", value, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountGreaterThan(Integer value) {
            addCriterion("created_account >", value, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_account >=", value, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountLessThan(Integer value) {
            addCriterion("created_account <", value, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountLessThanOrEqualTo(Integer value) {
            addCriterion("created_account <=", value, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountIn(List<Integer> values) {
            addCriterion("created_account in", values, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountNotIn(List<Integer> values) {
            addCriterion("created_account not in", values, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountBetween(Integer value1, Integer value2) {
            addCriterion("created_account between", value1, value2, "created_account");
            return (Criteria) this;
        }

        public Criteria andCreated_accountNotBetween(Integer value1, Integer value2) {
            addCriterion("created_account not between", value1, value2, "created_account");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeIsNull() {
            addCriterion("group_account_type is null");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeIsNotNull() {
            addCriterion("group_account_type is not null");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeEqualTo(Integer value) {
            addCriterion("group_account_type =", value, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeNotEqualTo(Integer value) {
            addCriterion("group_account_type <>", value, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeGreaterThan(Integer value) {
            addCriterion("group_account_type >", value, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_account_type >=", value, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeLessThan(Integer value) {
            addCriterion("group_account_type <", value, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeLessThanOrEqualTo(Integer value) {
            addCriterion("group_account_type <=", value, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeIn(List<Integer> values) {
            addCriterion("group_account_type in", values, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeNotIn(List<Integer> values) {
            addCriterion("group_account_type not in", values, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeBetween(Integer value1, Integer value2) {
            addCriterion("group_account_type between", value1, value2, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGroup_account_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("group_account_type not between", value1, value2, "group_account_type");
            return (Criteria) this;
        }

        public Criteria andGnameIsNull() {
            addCriterion("gname is null");
            return (Criteria) this;
        }

        public Criteria andGnameIsNotNull() {
            addCriterion("gname is not null");
            return (Criteria) this;
        }

        public Criteria andGnameEqualTo(String value) {
            addCriterion("gname =", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotEqualTo(String value) {
            addCriterion("gname <>", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThan(String value) {
            addCriterion("gname >", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThanOrEqualTo(String value) {
            addCriterion("gname >=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThan(String value) {
            addCriterion("gname <", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThanOrEqualTo(String value) {
            addCriterion("gname <=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLike(String value) {
            addCriterion("gname like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotLike(String value) {
            addCriterion("gname not like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameIn(List<String> values) {
            addCriterion("gname in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotIn(List<String> values) {
            addCriterion("gname not in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameBetween(String value1, String value2) {
            addCriterion("gname between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotBetween(String value1, String value2) {
            addCriterion("gname not between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andAvatorurlIsNull() {
            addCriterion("avatorurl is null");
            return (Criteria) this;
        }

        public Criteria andAvatorurlIsNotNull() {
            addCriterion("avatorurl is not null");
            return (Criteria) this;
        }

        public Criteria andAvatorurlEqualTo(String value) {
            addCriterion("avatorurl =", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlNotEqualTo(String value) {
            addCriterion("avatorurl <>", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlGreaterThan(String value) {
            addCriterion("avatorurl >", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlGreaterThanOrEqualTo(String value) {
            addCriterion("avatorurl >=", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlLessThan(String value) {
            addCriterion("avatorurl <", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlLessThanOrEqualTo(String value) {
            addCriterion("avatorurl <=", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlLike(String value) {
            addCriterion("avatorurl like", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlNotLike(String value) {
            addCriterion("avatorurl not like", value, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlIn(List<String> values) {
            addCriterion("avatorurl in", values, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlNotIn(List<String> values) {
            addCriterion("avatorurl not in", values, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlBetween(String value1, String value2) {
            addCriterion("avatorurl between", value1, value2, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andAvatorurlNotBetween(String value1, String value2) {
            addCriterion("avatorurl not between", value1, value2, "avatorurl");
            return (Criteria) this;
        }

        public Criteria andChat_typeIsNull() {
            addCriterion("chat_type is null");
            return (Criteria) this;
        }

        public Criteria andChat_typeIsNotNull() {
            addCriterion("chat_type is not null");
            return (Criteria) this;
        }

        public Criteria andChat_typeEqualTo(Integer value) {
            addCriterion("chat_type =", value, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeNotEqualTo(Integer value) {
            addCriterion("chat_type <>", value, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeGreaterThan(Integer value) {
            addCriterion("chat_type >", value, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("chat_type >=", value, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeLessThan(Integer value) {
            addCriterion("chat_type <", value, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeLessThanOrEqualTo(Integer value) {
            addCriterion("chat_type <=", value, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeIn(List<Integer> values) {
            addCriterion("chat_type in", values, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeNotIn(List<Integer> values) {
            addCriterion("chat_type not in", values, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeBetween(Integer value1, Integer value2) {
            addCriterion("chat_type between", value1, value2, "chat_type");
            return (Criteria) this;
        }

        public Criteria andChat_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("chat_type not between", value1, value2, "chat_type");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateEqualTo(Date value) {
            addCriterion("create_date =", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThan(Date value) {
            addCriterion("create_date >", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThan(Date value) {
            addCriterion("create_date <", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIn(List<Date> values) {
            addCriterion("create_date in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "create_date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.chat_group
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.chat_group
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}