package com.nesder.dao.entity;

import java.util.Date;

public class FllowAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fllow_account.fllowed_id
     *
     * @mbg.generated
     */
    private Integer fllowed_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fllow_account.fllower_id
     *
     * @mbg.generated
     */
    private Integer fllower_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.fllow_account.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fllow_account.fllowed_id
     *
     * @return the value of public.fllow_account.fllowed_id
     *
     * @mbg.generated
     */
    public Integer getFllowed_id() {
        return fllowed_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fllow_account.fllowed_id
     *
     * @param fllowed_id the value for public.fllow_account.fllowed_id
     *
     * @mbg.generated
     */
    public void setFllowed_id(Integer fllowed_id) {
        this.fllowed_id = fllowed_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fllow_account.fllower_id
     *
     * @return the value of public.fllow_account.fllower_id
     *
     * @mbg.generated
     */
    public Integer getFllower_id() {
        return fllower_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fllow_account.fllower_id
     *
     * @param fllower_id the value for public.fllow_account.fllower_id
     *
     * @mbg.generated
     */
    public void setFllower_id(Integer fllower_id) {
        this.fllower_id = fllower_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.fllow_account.create_date
     *
     * @return the value of public.fllow_account.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.fllow_account.create_date
     *
     * @param create_date the value for public.fllow_account.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}