package com.nesder.dao.entity;

import java.util.Date;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.module.module_id
     *
     * @mbg.generated
     */
    private Integer module_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.module.mname
     *
     * @mbg.generated
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.module.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.module.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.module.created_account
     *
     * @mbg.generated
     */
    private Integer created_account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.module.module_id
     *
     * @return the value of public.module.module_id
     *
     * @mbg.generated
     */
    public Integer getModule_id() {
        return module_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.module.module_id
     *
     * @param module_id the value for public.module.module_id
     *
     * @mbg.generated
     */
    public void setModule_id(Integer module_id) {
        this.module_id = module_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.module.mname
     *
     * @return the value of public.module.mname
     *
     * @mbg.generated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.module.mname
     *
     * @param mname the value for public.module.mname
     *
     * @mbg.generated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.module.create_date
     *
     * @return the value of public.module.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.module.create_date
     *
     * @param create_date the value for public.module.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.module.introduction
     *
     * @return the value of public.module.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.module.introduction
     *
     * @param introduction the value for public.module.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.module.created_account
     *
     * @return the value of public.module.created_account
     *
     * @mbg.generated
     */
    public Integer getCreated_account() {
        return created_account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.module.created_account
     *
     * @param created_account the value for public.module.created_account
     *
     * @mbg.generated
     */
    public void setCreated_account(Integer created_account) {
        this.created_account = created_account;
    }
}