package com.nesder.dao.entity;

import java.util.Date;

public class PostMediafiles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.post_id
     *
     * @mbg.generated
     */
    private Integer post_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_1
     *
     * @mbg.generated
     */
    private String image_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_2
     *
     * @mbg.generated
     */
    private String image_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_3
     *
     * @mbg.generated
     */
    private String image_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_4
     *
     * @mbg.generated
     */
    private String image_4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_5
     *
     * @mbg.generated
     */
    private String image_5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_6
     *
     * @mbg.generated
     */
    private String image_6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_7
     *
     * @mbg.generated
     */
    private String image_7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_8
     *
     * @mbg.generated
     */
    private String image_8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.image_9
     *
     * @mbg.generated
     */
    private String image_9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.video
     *
     * @mbg.generated
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.account_id
     *
     * @mbg.generated
     */
    private Integer account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.post_mediafiles.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.post_id
     *
     * @return the value of public.post_mediafiles.post_id
     *
     * @mbg.generated
     */
    public Integer getPost_id() {
        return post_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.post_id
     *
     * @param post_id the value for public.post_mediafiles.post_id
     *
     * @mbg.generated
     */
    public void setPost_id(Integer post_id) {
        this.post_id = post_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_1
     *
     * @return the value of public.post_mediafiles.image_1
     *
     * @mbg.generated
     */
    public String getImage_1() {
        return image_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_1
     *
     * @param image_1 the value for public.post_mediafiles.image_1
     *
     * @mbg.generated
     */
    public void setImage_1(String image_1) {
        this.image_1 = image_1 == null ? null : image_1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_2
     *
     * @return the value of public.post_mediafiles.image_2
     *
     * @mbg.generated
     */
    public String getImage_2() {
        return image_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_2
     *
     * @param image_2 the value for public.post_mediafiles.image_2
     *
     * @mbg.generated
     */
    public void setImage_2(String image_2) {
        this.image_2 = image_2 == null ? null : image_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_3
     *
     * @return the value of public.post_mediafiles.image_3
     *
     * @mbg.generated
     */
    public String getImage_3() {
        return image_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_3
     *
     * @param image_3 the value for public.post_mediafiles.image_3
     *
     * @mbg.generated
     */
    public void setImage_3(String image_3) {
        this.image_3 = image_3 == null ? null : image_3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_4
     *
     * @return the value of public.post_mediafiles.image_4
     *
     * @mbg.generated
     */
    public String getImage_4() {
        return image_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_4
     *
     * @param image_4 the value for public.post_mediafiles.image_4
     *
     * @mbg.generated
     */
    public void setImage_4(String image_4) {
        this.image_4 = image_4 == null ? null : image_4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_5
     *
     * @return the value of public.post_mediafiles.image_5
     *
     * @mbg.generated
     */
    public String getImage_5() {
        return image_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_5
     *
     * @param image_5 the value for public.post_mediafiles.image_5
     *
     * @mbg.generated
     */
    public void setImage_5(String image_5) {
        this.image_5 = image_5 == null ? null : image_5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_6
     *
     * @return the value of public.post_mediafiles.image_6
     *
     * @mbg.generated
     */
    public String getImage_6() {
        return image_6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_6
     *
     * @param image_6 the value for public.post_mediafiles.image_6
     *
     * @mbg.generated
     */
    public void setImage_6(String image_6) {
        this.image_6 = image_6 == null ? null : image_6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_7
     *
     * @return the value of public.post_mediafiles.image_7
     *
     * @mbg.generated
     */
    public String getImage_7() {
        return image_7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_7
     *
     * @param image_7 the value for public.post_mediafiles.image_7
     *
     * @mbg.generated
     */
    public void setImage_7(String image_7) {
        this.image_7 = image_7 == null ? null : image_7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_8
     *
     * @return the value of public.post_mediafiles.image_8
     *
     * @mbg.generated
     */
    public String getImage_8() {
        return image_8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_8
     *
     * @param image_8 the value for public.post_mediafiles.image_8
     *
     * @mbg.generated
     */
    public void setImage_8(String image_8) {
        this.image_8 = image_8 == null ? null : image_8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.image_9
     *
     * @return the value of public.post_mediafiles.image_9
     *
     * @mbg.generated
     */
    public String getImage_9() {
        return image_9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.image_9
     *
     * @param image_9 the value for public.post_mediafiles.image_9
     *
     * @mbg.generated
     */
    public void setImage_9(String image_9) {
        this.image_9 = image_9 == null ? null : image_9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.video
     *
     * @return the value of public.post_mediafiles.video
     *
     * @mbg.generated
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.video
     *
     * @param video the value for public.post_mediafiles.video
     *
     * @mbg.generated
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.account_id
     *
     * @return the value of public.post_mediafiles.account_id
     *
     * @mbg.generated
     */
    public Integer getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.account_id
     *
     * @param account_id the value for public.post_mediafiles.account_id
     *
     * @mbg.generated
     */
    public void setAccount_id(Integer account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.post_mediafiles.create_date
     *
     * @return the value of public.post_mediafiles.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.post_mediafiles.create_date
     *
     * @param create_date the value for public.post_mediafiles.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}