package com.nesder.dao.entity;

import java.util.Date;

public class Reply2Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.reply_2_reply_id
     *
     * @mbg.generated
     */
    private Integer reply_2_reply_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.modify_date
     *
     * @mbg.generated
     */
    private Date modify_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.rid
     *
     * @mbg.generated
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_2_reply.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.reply_2_reply_id
     *
     * @return the value of public.reply_2_reply.reply_2_reply_id
     *
     * @mbg.generated
     */
    public Integer getReply_2_reply_id() {
        return reply_2_reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.reply_2_reply_id
     *
     * @param reply_2_reply_id the value for public.reply_2_reply.reply_2_reply_id
     *
     * @mbg.generated
     */
    public void setReply_2_reply_id(Integer reply_2_reply_id) {
        this.reply_2_reply_id = reply_2_reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.content
     *
     * @return the value of public.reply_2_reply.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.content
     *
     * @param content the value for public.reply_2_reply.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.create_date
     *
     * @return the value of public.reply_2_reply.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.create_date
     *
     * @param create_date the value for public.reply_2_reply.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.modify_date
     *
     * @return the value of public.reply_2_reply.modify_date
     *
     * @mbg.generated
     */
    public Date getModify_date() {
        return modify_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.modify_date
     *
     * @param modify_date the value for public.reply_2_reply.modify_date
     *
     * @mbg.generated
     */
    public void setModify_date(Date modify_date) {
        this.modify_date = modify_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.rid
     *
     * @return the value of public.reply_2_reply.rid
     *
     * @mbg.generated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.rid
     *
     * @param rid the value for public.reply_2_reply.rid
     *
     * @mbg.generated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.uid
     *
     * @return the value of public.reply_2_reply.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.uid
     *
     * @param uid the value for public.reply_2_reply.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_2_reply.pid
     *
     * @return the value of public.reply_2_reply.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_2_reply.pid
     *
     * @param pid the value for public.reply_2_reply.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}