package com.nesder.dao.entity;

import java.util.Date;

public class ReplyLike {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_like.reply_id
     *
     * @mbg.generated
     */
    private Integer reply_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_like.likes
     *
     * @mbg.generated
     */
    private Boolean likes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_like.account_id
     *
     * @mbg.generated
     */
    private Integer account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply_like.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_like.reply_id
     *
     * @return the value of public.reply_like.reply_id
     *
     * @mbg.generated
     */
    public Integer getReply_id() {
        return reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_like.reply_id
     *
     * @param reply_id the value for public.reply_like.reply_id
     *
     * @mbg.generated
     */
    public void setReply_id(Integer reply_id) {
        this.reply_id = reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_like.likes
     *
     * @return the value of public.reply_like.likes
     *
     * @mbg.generated
     */
    public Boolean getLikes() {
        return likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_like.likes
     *
     * @param likes the value for public.reply_like.likes
     *
     * @mbg.generated
     */
    public void setLikes(Boolean likes) {
        this.likes = likes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_like.account_id
     *
     * @return the value of public.reply_like.account_id
     *
     * @mbg.generated
     */
    public Integer getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_like.account_id
     *
     * @param account_id the value for public.reply_like.account_id
     *
     * @mbg.generated
     */
    public void setAccount_id(Integer account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply_like.create_date
     *
     * @return the value of public.reply_like.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply_like.create_date
     *
     * @param create_date the value for public.reply_like.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}