package com.nesder.dao.entity;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.reply_id
     *
     * @mbg.generated
     */
    private Integer reply_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.modify_date
     *
     * @mbg.generated
     */
    private Date modify_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.enable_edit
     *
     * @mbg.generated
     */
    private Boolean enable_edit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.reply_to_account_id
     *
     * @mbg.generated
     */
    private Integer reply_to_account_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.reply_to_reply_id
     *
     * @mbg.generated
     */
    private Integer reply_to_reply_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.post_id
     *
     * @mbg.generated
     */
    private Integer post_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reply.account_id
     *
     * @mbg.generated
     */
    private Integer account_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.reply_id
     *
     * @return the value of public.reply.reply_id
     *
     * @mbg.generated
     */
    public Integer getReply_id() {
        return reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.reply_id
     *
     * @param reply_id the value for public.reply.reply_id
     *
     * @mbg.generated
     */
    public void setReply_id(Integer reply_id) {
        this.reply_id = reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.content
     *
     * @return the value of public.reply.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.content
     *
     * @param content the value for public.reply.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.create_date
     *
     * @return the value of public.reply.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.create_date
     *
     * @param create_date the value for public.reply.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.modify_date
     *
     * @return the value of public.reply.modify_date
     *
     * @mbg.generated
     */
    public Date getModify_date() {
        return modify_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.modify_date
     *
     * @param modify_date the value for public.reply.modify_date
     *
     * @mbg.generated
     */
    public void setModify_date(Date modify_date) {
        this.modify_date = modify_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.enable_edit
     *
     * @return the value of public.reply.enable_edit
     *
     * @mbg.generated
     */
    public Boolean getEnable_edit() {
        return enable_edit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.enable_edit
     *
     * @param enable_edit the value for public.reply.enable_edit
     *
     * @mbg.generated
     */
    public void setEnable_edit(Boolean enable_edit) {
        this.enable_edit = enable_edit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.reply_to_account_id
     *
     * @return the value of public.reply.reply_to_account_id
     *
     * @mbg.generated
     */
    public Integer getReply_to_account_id() {
        return reply_to_account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.reply_to_account_id
     *
     * @param reply_to_account_id the value for public.reply.reply_to_account_id
     *
     * @mbg.generated
     */
    public void setReply_to_account_id(Integer reply_to_account_id) {
        this.reply_to_account_id = reply_to_account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.reply_to_reply_id
     *
     * @return the value of public.reply.reply_to_reply_id
     *
     * @mbg.generated
     */
    public Integer getReply_to_reply_id() {
        return reply_to_reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.reply_to_reply_id
     *
     * @param reply_to_reply_id the value for public.reply.reply_to_reply_id
     *
     * @mbg.generated
     */
    public void setReply_to_reply_id(Integer reply_to_reply_id) {
        this.reply_to_reply_id = reply_to_reply_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.post_id
     *
     * @return the value of public.reply.post_id
     *
     * @mbg.generated
     */
    public Integer getPost_id() {
        return post_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.post_id
     *
     * @param post_id the value for public.reply.post_id
     *
     * @mbg.generated
     */
    public void setPost_id(Integer post_id) {
        this.post_id = post_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reply.account_id
     *
     * @return the value of public.reply.account_id
     *
     * @mbg.generated
     */
    public Integer getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reply.account_id
     *
     * @param account_id the value for public.reply.account_id
     *
     * @mbg.generated
     */
    public void setAccount_id(Integer account_id) {
        this.account_id = account_id;
    }
}